import { BedDouble, Building2, CheckCircle2, Clock3, FileText, ShieldCheck, UsersRound, XCircle } from 'lucide-react'
import { PageHeader } from '../../components/common/PageHeader'
import { AdminPageState } from '../dormitory-admin/AdminPageState'
import { AdminStatusBadge } from '../dormitory-admin/AdminStatusBadge'
import { getApiErrorMessage } from '../../utils/apiError'
import { useAuth } from '../auth/useAuth'
import { useGlobalDashboard } from './globalAdminQueries'

const processLabels={NOT_STARTED:'Başlamadı',IN_PROGRESS:'Devam Ediyor',COMPLETED:'Tamamlandı'} as const
function Stat({label,value}:{label:string;value:number}){return <div className="border border-slate-200 bg-white p-4 shadow-sm"><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-2xl font-semibold text-slate-950">{value}</p></div>}

export function GlobalDashboardPage(){const{user}=useAuth();const q=useGlobalDashboard(user?.userId??0);return <section><PageHeader title="Genel Kontrol Paneli" description="Tüm yurtların kapasite, kabul, kullanıcı ve belge süreçlerini sistem genelinde izleyin." />{q.isLoading&&<AdminPageState state="loading" title="Genel panel yükleniyor" message="Sistem istatistikleri alınıyor..."/>}{q.isError&&<AdminPageState state="error" title="Genel panel yüklenemedi" message={getApiErrorMessage(q.error,'Genel yönetim verileri alınamadı.')} onRetry={()=>void q.refetch()}/>} {q.isSuccess&&(()=>{const d=q.data;return <div className="mt-6 space-y-7"><article className="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-sm font-medium text-blue-800">Aktif dönem</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold text-slate-950">{d.activeTermName}</h2><p className="mt-1 text-sm text-slate-600">{d.firstName} {d.lastName} · {d.email}</p></div><AdminStatusBadge label="GLOBAL Yönetim" tone="info"/></div></article>
<section><h2 className="text-lg font-semibold text-slate-950">Sistem kapasitesi</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Toplam yurt" value={d.totalDormitoryCount}/><Stat label="Toplam kapasite" value={d.totalCapacity}/><Stat label="Aktif öğrenci" value={d.activeStudentCount}/><Stat label="Kullanılabilir kapasite" value={d.availableCapacity}/></div><div className="mt-3 h-2.5 bg-slate-200" role="progressbar" aria-label="Sistem doluluk oranı" aria-valuemin={0} aria-valuemax={100} aria-valuenow={d.occupancyPercentage}><div className="h-full bg-blue-700" style={{width:`${Math.min(d.occupancyPercentage,100)}%`}}/></div><p className="mt-2 text-sm text-slate-600">Doluluk: %{d.occupancyPercentage} · Aktif yurt: {d.activeDormitoryCount} · Pasif yurt: {d.inactiveDormitoryCount}</p></section>
<div className="grid gap-7 xl:grid-cols-3"><section><h2 className="text-lg font-semibold">Kabuller</h2><div className="mt-3 grid gap-2"><Stat label="Toplam" value={d.totalAdmissionCount}/><Stat label="Bekleyen" value={d.pendingAdmissionCount}/><Stat label="Onaylanan" value={d.approvedAdmissionCount}/><Stat label="Reddedilen" value={d.rejectedAdmissionCount}/></div></section><section><h2 className="text-lg font-semibold">Belge süreci</h2><div className="mt-3 grid gap-2"><Stat label="Bekleyen" value={d.pendingDocumentCount}/><Stat label="Onaylanan" value={d.approvedDocumentCount}/><Stat label="Düzeltme" value={d.revisionRequiredDocumentCount}/><Stat label="Reddedilen" value={d.rejectedDocumentCount}/></div></section><section><h2 className="text-lg font-semibold">Kullanıcılar</h2><div className="mt-3 grid gap-2"><Stat label="Admin" value={d.totalAdminCount}/><Stat label="Global / Yurt admini" value={d.globalAdminCount+d.dormitoryAdminCount}/><Stat label="Değerlendirici" value={d.totalReviewerCount}/><Stat label="Öğrenci kullanıcısı" value={d.totalStudentUserCount}/></div></section></div>
<section className="border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">Öğrenci belge tamamlanması</h2><p className="mt-1 text-sm text-slate-600">Tamamlanan {d.completedStudentCount} · Tamamlanmayan {d.incompleteStudentCount} · İşlem gereken {d.actionRequiredStudentCount}</p></div><strong className="text-2xl">%{d.studentCompletionPercentage}</strong></div></section>
<section><h2 className="text-lg font-semibold text-slate-950">Yurt bazında süreç görünümü</h2><p className="mt-1 text-sm text-slate-600">Kabulü tamamlanan {d.admissionCompletedDormitoryCount}, devam eden {d.admissionInProgressDormitoryCount} yurt.</p>{d.dormitoryStatistics.length===0?<div className="mt-4 border p-5 text-sm">Yurt istatistiği bulunmuyor.</div>:<div className="mt-4 grid gap-4 xl:grid-cols-2">{d.dormitoryStatistics.map(s=><article key={s.dormitoryId} className="border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-3"><Building2 aria-hidden="true" className="text-blue-700"/><div><h3 className="font-semibold">{s.dormitoryName}</h3><p className="mt-1 text-sm text-slate-600">{s.manager?`${s.manager.firstName} ${s.manager.lastName}`:'Yönetici atanmamış'}</p></div></div><AdminStatusBadge label={processLabels[s.admissionProcessStatus]} tone={s.admissionProcessStatus==='COMPLETED'?'success':s.admissionProcessStatus==='IN_PROGRESS'?'warning':'neutral'}/></div><p className="mt-3 text-sm leading-6 text-slate-600">{s.admissionProcessMessage}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><span><BedDouble className="mb-1" size={17}/>Kapasite <strong className="block">{s.capacity}</strong></span><span><UsersRound className="mb-1" size={17}/>Öğrenci <strong className="block">{s.activeStudentCount}</strong></span><span><ShieldCheck className="mb-1" size={17}/>Reviewer <strong className="block">{s.totalReviewerCount}</strong></span><span><FileText className="mb-1" size={17}/>Bekleyen <strong className="block">{s.pendingDocumentCount}</strong></span></div><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="bg-emerald-50 px-2 py-1 text-emerald-700"><CheckCircle2 className="mr-1 inline" size={14}/>Onay {s.approvedAdmissionCount}</span><span className="bg-amber-50 px-2 py-1 text-amber-800"><Clock3 className="mr-1 inline" size={14}/>Bekleyen {s.pendingAdmissionCount}</span><span className="bg-red-50 px-2 py-1 text-red-700"><XCircle className="mr-1 inline" size={14}/>Ret {s.rejectedAdmissionCount}</span></div><p className="mt-4 text-xs text-slate-500">Doluluk %{s.occupancyPercentage} · Belge tamamlanması %{s.studentCompletionPercentage} · İşlem gereken öğrenci {s.actionRequiredStudentCount}</p></article>)}</div>}</section></div>})()}</section>}
