import { Search, UserRound } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../../components/common/PageHeader'
import { getApiErrorMessage } from '../../utils/apiError'
import { formatDate } from '../../utils/formatDate'
import { useAuth } from '../auth/useAuth'
import { AdminPageState } from '../dormitory-admin/AdminPageState'
import { useGlobalStudents } from './globalAdminQueries'

export function GlobalStudentsPage(){const{user}=useAuth();const q=useGlobalStudents(user?.userId??0);const[s,setS]=useState('');const n=s.trim().toLocaleLowerCase('tr-TR');const list=(q.data??[]).filter(x=>!n||`${x.firstName} ${x.lastName} ${x.email} ${x.identityNumber}`.toLocaleLowerCase('tr-TR').includes(n));return <section><PageHeader title="Öğrenciler" description="Sistemde kayıtlı tüm öğrenci profillerini görüntüleyin."/>{q.isLoading&&<AdminPageState state="loading" title="Öğrenciler yükleniyor" message="Öğrenci profilleri alınıyor..."/>}{q.isError&&<AdminPageState state="error" title="Öğrenciler alınamadı" message={getApiErrorMessage(q.error,'Öğrenciler alınamadı.')} onRetry={()=>void q.refetch()}/>} {q.isSuccess&&q.data.length===0&&<AdminPageState state="empty" title="Öğrenci yok" message="Sistemde öğrenci profili bulunmuyor."/>}{q.isSuccess&&q.data.length>0&&<div className="mt-6"><div className="relative max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><label className="sr-only" htmlFor="gs">Öğrenci ara</label><input id="gs" value={s} onChange={e=>setS(e.target.value)} className="min-h-11 w-full border pl-10 pr-3" placeholder="Ad, e-posta veya kimlik no ara"/></div>{list.length===0?<div className="mt-4 border bg-white p-6 text-center">Eşleşen öğrenci yok.</div>:<div className="mt-4 grid gap-3 lg:grid-cols-2">{list.map(x=><article key={x.id} className="border bg-white p-4"><div className="flex gap-3"><UserRound className="text-blue-700"/><div><h2 className="font-semibold">{x.firstName} {x.lastName}</h2><p className="text-sm text-slate-600">{x.email}</p></div></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-slate-500">Kimlik</dt><dd>{x.identityNumber}</dd></div><div><dt className="text-slate-500">Telefon</dt><dd>{x.phone}</dd></div><div><dt className="text-slate-500">Fakülte</dt><dd>{x.faculty}</dd></div><div><dt className="text-slate-500">Bölüm</dt><dd>{x.department}</dd></div><div><dt className="text-slate-500">Doğum tarihi</dt><dd>{formatDate(x.birthDate)}</dd></div></dl></article>)}</div>}</div>}</section>}
