import { Check, LoaderCircle, X } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { PageHeader } from '../../components/common/PageHeader'
import type { AdmissionStatus } from '../../types/student'
import { formatDate } from '../../utils/formatDate'
import { getApiErrorMessage } from '../../utils/apiError'
import { useAuth } from '../auth/useAuth'
import { AdminPageState } from '../dormitory-admin/AdminPageState'
import { AdminStatusBadge } from '../dormitory-admin/AdminStatusBadge'
import { adminAdmissionPresentation } from '../dormitory-admin/adminPresentation'
import { useAdmissionMutation, useGlobalAdmissions } from './globalAdminQueries'

export function GlobalAdmissionsPage(){const{user}=useAuth();const u=user?.userId??0;const q=useGlobalAdmissions(u);const m=useAdmissionMutation(u);const[f,setF]=useState<'ALL'|AdmissionStatus>('ALL');const list=(q.data??[]).filter(x=>f==='ALL'||x.status===f);const decide=(id:number,status:'APPROVED'|'REJECTED',name:string)=>{if(!window.confirm(`${name} kabul kaydı ${status==='APPROVED'?'onaylansın':'reddedilsin'} mi? Karar geri alınamaz.`))return;m.mutate({id,status},{onSuccess:()=>toast.success('Kabul durumu güncellendi.'),onError:e=>toast.error(getApiErrorMessage(e,'Kabul güncellenemedi.'))})};return <section><PageHeader title="Kabuller" description="Aktif dönemde tüm yurtlara ait kabul kayıtlarını izleyin ve bekleyen kayıtları karara bağlayın."/>{q.isLoading&&<AdminPageState state="loading" title="Kabuller yükleniyor" message="Global kabul kayıtları alınıyor..."/>}{q.isError&&<AdminPageState state="error" title="Kabuller alınamadı" message={getApiErrorMessage(q.error,'Kabuller alınamadı.')} onRetry={()=>void q.refetch()}/>} {q.isSuccess&&q.data.length===0&&<AdminPageState state="empty" title="Kabul yok" message="Aktif dönemde kabul kaydı bulunmuyor."/>}{q.isSuccess&&q.data.length>0&&<div className="mt-6"><div className="flex flex-wrap gap-2">{(['ALL','PENDING','APPROVED','REJECTED'] as const).map(x=><button key={x} onClick={()=>setF(x)} className={`border px-3 py-2 text-sm ${f===x?'bg-blue-800 text-white':''}`}>{x==='ALL'?'Tümü':adminAdmissionPresentation[x].label}</button>)}</div><div className="mt-4 grid gap-3 lg:grid-cols-2">{list.map(a=>{const p=adminAdmissionPresentation[a.status],pending=m.isPending&&m.variables?.id===a.id,name=`${a.studentFirstName} ${a.studentLastName}`;return <article key={a.id} className="border bg-white p-4"><div className="flex justify-between gap-2"><div><h2 className="font-semibold">{name}</h2><p className="text-sm text-slate-600">{a.dormitoryName} · {a.dormitoryTermName}</p></div><AdminStatusBadge label={p.label} tone={p.tone}/></div><p className="mt-3 text-sm">Kabul tarihi: {formatDate(a.admissionDate)} · Kimlik: {a.identityNumber}</p>{a.status==='PENDING'&&<div className="mt-4 flex gap-2"><button disabled={pending} onClick={()=>decide(a.id,'APPROVED',name)} className="bg-emerald-700 px-3 py-2 text-sm text-white">{pending?<LoaderCircle className="inline animate-spin" size={16}/>:<Check className="inline" size={16}/>} Onayla</button><button disabled={pending} onClick={()=>decide(a.id,'REJECTED',name)} className="border border-red-700 px-3 py-2 text-sm text-red-700"><X className="inline" size={16}/> Reddet</button></div>}</article>})}</div></div>}</section>}
