import { AlertTriangle, BedDouble, CheckCircle2, Clock3, FileCheck2, RefreshCw, UserCheck, UsersRound, XCircle } from 'lucide-react'
import { PageHeader } from '../../components/common/PageHeader'
import { getApiErrorMessage } from '../../utils/apiError'
import { useAuth } from '../auth/useAuth'
import { AdminPageState } from './AdminPageState'
import { AdminStatusBadge } from './AdminStatusBadge'
import { useDormitoryAdminDashboard } from './dormitoryAdminQueries'

interface StatProps { label: string; value: number; icon: typeof BedDouble; color: string }
function Stat({ label, value, icon: Icon, color }: StatProps) {
  return <article className="border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-2xl font-semibold text-slate-950">{value}</p></div><span className={`flex size-10 items-center justify-center ${color}`}><Icon aria-hidden="true" size={20} /></span></div></article>
}

export function DormitoryAdminDashboardPage() {
  const { user } = useAuth()
  const query = useDormitoryAdminDashboard(user?.userId ?? 0)
  return <section><PageHeader title="Yurt Yönetim Paneli" description="Yurdunuzun kapasite, kabul, belge ve değerlendirici süreçlerini güncel verilerle izleyin." />
    {query.isLoading && <AdminPageState state="loading" title="Yönetim paneli yükleniyor" message="Yurdunuzun güncel operasyon bilgileri alınıyor..." />}
    {query.isError && <AdminPageState state="error" title="Yönetim paneli yüklenemedi" message={getApiErrorMessage(query.error, 'Yurt yönetim paneli alınamadı.')} onRetry={() => void query.refetch()} />}
    {query.isSuccess && (() => { const d = query.data; return <div className="mt-6 space-y-7">
      <article className="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-sm font-medium text-blue-800">Yurt ve aktif dönem</p><div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold text-slate-950">{d.dormitoryName}</h2><p className="mt-1 text-sm text-slate-600">{d.activeTermName}</p></div><p className="text-sm text-slate-600">{d.firstName} {d.lastName} · {d.email}</p></div></article>

      <section aria-labelledby="capacity-title"><h2 id="capacity-title" className="text-lg font-semibold text-slate-950">Kapasite ve doluluk</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Toplam kapasite" value={d.capacity} icon={BedDouble} color="bg-blue-50 text-blue-700" /><Stat label="Aktif öğrenci" value={d.activeStudentCount} icon={UsersRound} color="bg-slate-100 text-slate-700" /><Stat label="Kullanılabilir kapasite" value={d.availableCapacity} icon={BedDouble} color="bg-emerald-50 text-emerald-700" /><Stat label="Doluluk oranı (%)" value={d.occupancyPercentage} icon={UserCheck} color="bg-amber-50 text-amber-700" /></div><div className="mt-3 h-2.5 overflow-hidden bg-slate-200" role="progressbar" aria-label="Yurt doluluk oranı" aria-valuemin={0} aria-valuemax={100} aria-valuenow={d.occupancyPercentage}><div className="h-full bg-blue-700" style={{ width: `${Math.min(d.occupancyPercentage, 100)}%` }} /></div></section>

      <div className="grid gap-7 xl:grid-cols-2">
        <section aria-labelledby="admission-summary-title"><h2 id="admission-summary-title" className="text-lg font-semibold text-slate-950">Kabul Durumu</h2><p className="mt-1 text-sm text-slate-600">Kabul kayıtlarının başvuru sonucunu gösterir; belge tamamlanmasından bağımsızdır.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Stat label="Toplam kabul" value={d.totalAdmissionCount} icon={UsersRound} color="bg-slate-100 text-slate-700" /><Stat label="Kabul bekleyen" value={d.pendingAdmissionCount} icon={Clock3} color="bg-amber-50 text-amber-700" /><Stat label="Kabul edilen" value={d.approvedAdmissionCount} icon={CheckCircle2} color="bg-emerald-50 text-emerald-700" /><Stat label="Reddedilen" value={d.rejectedAdmissionCount} icon={XCircle} color="bg-red-50 text-red-700" /></div></section>
        <section aria-labelledby="document-summary-title"><h2 id="document-summary-title" className="text-lg font-semibold text-slate-950">Belge durumu</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Stat label="Bekleyen" value={d.pendingDocumentCount} icon={Clock3} color="bg-blue-50 text-blue-700" /><Stat label="Onaylanan" value={d.approvedDocumentCount} icon={FileCheck2} color="bg-emerald-50 text-emerald-700" /><Stat label="Düzeltme gereken" value={d.revisionRequiredDocumentCount} icon={RefreshCw} color="bg-amber-50 text-amber-700" /><Stat label="Reddedilen" value={d.rejectedDocumentCount} icon={XCircle} color="bg-red-50 text-red-700" /></div></section>
      </div>

      <section aria-labelledby="completion-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="completion-title" className="text-lg font-semibold text-slate-950">Öğrenci Belge Süreci</h2><p className="mt-1 text-sm text-slate-600">Zorunlu belgelerin onaylanma durumuna göre operasyonel ilerleme.</p></div><p className="text-sm font-semibold text-slate-700">Tamamlanma oranı: %{d.studentCompletionPercentage}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Toplam öğrenci" value={d.activeStudentCount} icon={UsersRound} color="bg-slate-100 text-slate-700" /><Stat label="Bekleyen" value={d.incompleteStudentCount} icon={Clock3} color="bg-amber-50 text-amber-700" /><Stat label="Tamamlanan" value={d.completedStudentCount} icon={FileCheck2} color="bg-emerald-50 text-emerald-700" /><Stat label="Tamamlanma oranı (%)" value={d.studentCompletionPercentage} icon={CheckCircle2} color="bg-blue-50 text-blue-700" /></div><div className="mt-3 h-2.5 overflow-hidden bg-slate-200" role="progressbar" aria-label="Öğrenci belge tamamlama oranı" aria-valuemin={0} aria-valuemax={100} aria-valuenow={d.studentCompletionPercentage}><div className="h-full bg-emerald-600" style={{ width: `${Math.min(d.studentCompletionPercentage, 100)}%` }} /></div></section>

      <section aria-labelledby="reviewers-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="reviewers-title" className="text-lg font-semibold text-slate-950">Değerlendirici iş yükü</h2><p className="mt-1 text-sm text-slate-600">Aktif dönemde kaydedilen değerlendirme adetleri.</p></div><div className="flex gap-2"><AdminStatusBadge label={`Aktif: ${d.activeReviewerCount}`} tone="success" /><AdminStatusBadge label={`Pasif: ${d.inactiveReviewerCount}`} tone="neutral" /></div></div>{d.reviewerWorkloads.length === 0 ? <div className="mt-4 border border-slate-200 bg-white p-5 text-sm text-slate-600">Yurda bağlı değerlendirici bulunmuyor.</div> : <div className="mt-4 grid gap-3 lg:grid-cols-2">{d.reviewerWorkloads.map((r) => <article key={r.reviewerId} className="border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900">{r.firstName} {r.lastName}</h3><p className="mt-1 text-sm text-slate-600">{r.email}</p></div><AdminStatusBadge label={r.active ? 'Aktif' : 'Pasif'} tone={r.active ? 'success' : 'neutral'} /></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-600"><span>Toplam: {r.totalReviewCount}</span><span>Onay: {r.approvedReviewCount}</span><span>Ret: {r.rejectedReviewCount}</span><span>Düzeltme: {r.revisionRequiredReviewCount}</span></div></article>)}</div>}</section>

      <div className="grid gap-7 xl:grid-cols-2"><section aria-labelledby="pending-types-admin"><h2 id="pending-types-admin" className="text-lg font-semibold text-slate-950">Türüne göre bekleyen belgeler</h2>{d.pendingDocumentsByType.length === 0 ? <div className="mt-4 border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800">Bekleyen belge bulunmuyor.</div> : <div className="mt-4 divide-y divide-slate-200 border border-slate-200 bg-white">{d.pendingDocumentsByType.map((x) => <div key={x.documentTypeId} className="flex items-center justify-between gap-2 px-4 py-3 text-sm"><span>{x.documentTypeName}</span><strong>{x.pendingCount}</strong></div>)}</div>}</section><section aria-labelledby="action-students-admin"><h2 id="action-students-admin" className="text-lg font-semibold text-slate-950">İşlem gereken öğrenciler</h2><p className="mt-1 text-sm text-slate-600">Backend tarafından önceliklendirilen ilk 10 kayıt.</p>{d.actionRequiredStudents.length === 0 ? <div className="mt-4 border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800">İşlem gereken öğrenci bulunmuyor.</div> : <div className="mt-4 space-y-3">{d.actionRequiredStudents.map((s) => <article key={s.admissionId} className="border border-slate-200 bg-white p-4"><div className="flex items-start gap-2"><AlertTriangle aria-hidden="true" className="mt-0.5 text-amber-700" size={18} /><div><h3 className="font-semibold text-slate-900">{s.firstName} {s.lastName}</h3><p className="mt-2 text-xs text-slate-600">Eksik {s.missingDocumentCount} · Düzeltme {s.revisionRequiredDocumentCount} · Ret {s.rejectedDocumentCount}</p></div></div></article>)}</div>}</section></div>
    </div> })()}
  </section>
}
