spring.application.name=yurtlar

# ACTUATOR / METRICS
management.server.port=${MANAGEMENT_SERVER_PORT:8081}
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT:1s}
spring.data.redis.timeout=${REDIS_TIMEOUT:1s}

# ELASTICSEARCH
spring.elasticsearch.uris=${ELASTICSEARCH_URIS:http://localhost:9200}
app.elasticsearch.audit-index=${AUDIT_ELASTICSEARCH_INDEX:yurtlar-audit-log-v1}

app.file-storage.upload-dir=uploads

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000

# KAFKA
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.group-id=yurtlar-learning-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# OUTBOX PUBLISHER
outbox.publisher.fixed-delay-ms=2000
outbox.publisher.initial-delay-ms=3000
