package com.ibb.yurtlar.enums;

public enum AuditAction {
    ADMISSION_APPROVED, ADMISSION_REJECTED,
    DOCUMENT_UPLOADED, DOCUMENT_REUPLOADED, DOCUMENT_PROCESS_COMPLETED,
    DOCUMENT_APPROVED, DOCUMENT_REJECTED, DOCUMENT_REVISION_REQUIRED,
    DORMITORY_CREATED, DORMITORY_UPDATED,
    USER_CREATED, USER_UPDATED, USER_ACTIVATED, USER_DEACTIVATED,
    TERM_CREATED, TERM_UPDATED, TERM_ACTIVATED, TERM_DEACTIVATED, TERM_DELETED,
    DOCUMENT_TYPE_CREATED, DOCUMENT_TYPE_UPDATED,
    REQUIREMENT_CREATED, REQUIREMENT_UPDATED
}
