package com.ibb.yurtlar.enums;

public enum NotificationType {

    ADMISSION_APPROVED,
    ADMISSION_REJECTED,

    DOCUMENT_UPLOADED,
    DOCUMENT_REUPLOADED,

    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_REVISION_REQUIRED,

    DOCUMENT_PROCESS_COMPLETED
}